### ISSUE TITLE
All the IoT assets not showing in persistent mongodb

### ISSUE THREAD

**Issue by utkarshmankad** [Fiware/tutorials.Historic-Context#12]
I followed the instructions as per the README.md, and setup the mongo db historic context persistence architecture. 
While I tried generating the context, I unlocked all 4 doors, and turned ON all lamps.
However, when I tried to see the tables, of the items generating context, I could see 1 door, 4 lamps, 4 motion sensors,
and no 4 doors, 4 lamps, 4 motion sensors. 
Why is this so, is there some bug in the system or the setup ? Please explain the reason for this. 
Thanks in advance

**Comment by utkarshmankad** [comment]
However, over time, all the assets appear in persisted mongodb. But why arent they populated instantly, even though the contexts created are almost simultaneously ?

**Comment by jason-fox** [comment]
Within the tutorial, the subscription request includes a `throttling` attribute:

```console
curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify Cygnus Mongo-DB of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5051/notify"
    }
  },
  "throttling": 5
}'
```

This means that a record is only persisted once every five seconds. Since the devices are effectively firing at random, this translates into a race condition - whichever Device fires first is the one which is updated for that window.  This is more explicitly described [here](https://github.com/FIWARE/tutorials.Short-Term-History/blob/master/README.md#sth-comet---sample-lamp-luminosity)

**Comment by utkarshmankad** [comment]
Ok, understood !! Thanks for the detailed explanation.
Thanks and Regards,
